import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 

const opener = localFont({
  src: "../public/fonts/opener/Opener.ttf",
  variable: "--font-opener",
});
const inter = localFont({
  src: "../public/fonts/inter/inter.ttf",
  variable: "--font-inter",
});
const sansfont = localFont({
  src: "../public/fonts/sans/sans.ttf",
  variable: "--font-sansfont",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${opener.variable} ${inter.variable} ${sansfont.variable} h-full antialiased bg-black `}
    >
      <body className="min-h-full flex flex-col  ">{children}</body>
    </html>
  );
}
